import { EVVehicle, GridState } from '../types';

export const INITIAL_EVS: EVVehicle[] = [
  {
    id: 'PORT-01',
    model: 'Tesla Model 3',
    batterySoc: 20,
    batteryCapacityKwh: 60,
    targetSoc: 85,
    maxChargingRateKw: 11.0,
    currentChargingRateKw: 7.0,
    departureTime: '07:00 AM',
    departureHoursRemaining: 2.5,
    requiredEnergyKwh: 39.0,
    priorityScore: 88,
    priorityLevel: 'VERY HIGH',
    isConnected: true,
    status: 'CHARGING',
    consecutiveHighChargingMinutes: 15,
    totalChargedKwh: 4.8,
    fairnessFactor: 1.0,
    arrivalOrder: 1,
  },
  {
    id: 'PORT-02',
    model: 'Hyundai Ioniq 5',
    batterySoc: 65,
    batteryCapacityKwh: 77.4,
    targetSoc: 90,
    maxChargingRateKw: 11.0,
    currentChargingRateKw: 4.0,
    departureTime: '05:00 PM',
    departureHoursRemaining: 10.0,
    requiredEnergyKwh: 19.35,
    priorityScore: 42,
    priorityLevel: 'MEDIUM',
    isConnected: true,
    status: 'CHARGING',
    consecutiveHighChargingMinutes: 5,
    totalChargedKwh: 6.2,
    fairnessFactor: 1.0,
    arrivalOrder: 2,
  },
  {
    id: 'PORT-03',
    model: 'Kia EV6',
    batterySoc: 38,
    batteryCapacityKwh: 64.0,
    targetSoc: 80,
    maxChargingRateKw: 11.0,
    currentChargingRateKw: 6.0,
    departureTime: '08:00 AM',
    departureHoursRemaining: 3.5,
    requiredEnergyKwh: 26.88,
    priorityScore: 74,
    priorityLevel: 'HIGH',
    isConnected: true,
    status: 'CHARGING',
    consecutiveHighChargingMinutes: 20,
    totalChargedKwh: 8.5,
    fairnessFactor: 1.0,
    arrivalOrder: 3,
  },
  {
    id: 'PORT-04',
    model: 'Nissan Leaf Plus',
    batterySoc: 72,
    batteryCapacityKwh: 62.0,
    targetSoc: 90,
    maxChargingRateKw: 6.6,
    currentChargingRateKw: 3.0,
    departureTime: '06:00 PM',
    departureHoursRemaining: 11.0,
    requiredEnergyKwh: 11.16,
    priorityScore: 32,
    priorityLevel: 'MEDIUM',
    isConnected: true,
    status: 'CHARGING',
    consecutiveHighChargingMinutes: 0,
    totalChargedKwh: 3.1,
    fairnessFactor: 1.0,
    arrivalOrder: 4,
  },
  {
    id: 'PORT-05',
    model: 'MG ZS EV',
    batterySoc: 35,
    batteryCapacityKwh: 50.3,
    targetSoc: 85,
    maxChargingRateKw: 7.4,
    currentChargingRateKw: 3.5,
    departureTime: '09:30 AM',
    departureHoursRemaining: 4.5,
    requiredEnergyKwh: 25.15,
    priorityScore: 64,
    priorityLevel: 'HIGH',
    isConnected: true,
    status: 'CHARGING',
    consecutiveHighChargingMinutes: 8,
    totalChargedKwh: 4.2,
    fairnessFactor: 1.0,
    arrivalOrder: 5,
  },
];

export const INITIAL_GRID_STATE: GridState = {
  gridLimitKw: 50.0,
  transformerCapacityKw: 60.0,
  buildingDemandKw: 30.0,
  solarGenerationKw: 14.5,
  evChargingLoadKw: 20.0,
  totalLoadKw: 35.5, // (30 - 14.5 = 15.5 net building + 20 EV = 35.5 kW drawn from grid)
  availableGridCapacityKw: 20.0,
  solarSurplusKw: 0.0,
  availableChargingCapacityKw: 34.5,
  systemStatus: 'SAFE',
  statusMessage: 'Cluster operating safely within grid and transformer envelopes.',
  activeScenario: 'NORMAL',
  lastOverloadPrevention: null,
};
